export enum ForgotUserNamePasswordActions {
    ANSWER_SECURITY_CODE_CONTINUE_PRESSED = 'AnswerSecurityCodeContinuePressed',
    ANSWER_SECURITY_QUESTION_CONTINUE_PRESSED = 'AnswerSecurityQuestionContinuePressed',
    FINDUSER_FIND_MY_INFO_PRESSED = 'FindUserFindMyInfoPressed',
    FINDUSER_FORGOT_PASSWORD_PRESSED = 'FindUserForgotPasswordPressed',
    FIND_USER_FORGOT_USERNAME_PRESSED = 'FindUserForgotUsernamePressed',
    FORGOT_PASSWORD_2FA_PRESSED = 'ForgotPassword2FAPressed',
    FORGOT_PASSWORD_2FA_SEND_CODE_PRESSED = 'ForgotPassword2FASendCodePressed',
    FORGOT_USERNAME_2FA_PRESSED = 'ForgotUsername2FAPressed',
    FORGOT_USERNAME_2FA_SEND_CODE_PRESSED = 'ForgotUserName2FASendCodePressed',
    FORGOT_USERNAME_PASSWORD_CANCELED = 'FindUserCancelPressed',
    FORGOT_USERNAME_PASSWORD_SUCCESS_MODAL_PRESSED = 'ForgotUsernamePasswordSuccessModalPressed',
    LOGIN_NAVIGATION_LINK_PRESSED = 'LoginNavigationLinkPressed',
    OTP_ANSWER_SECURITY_QUESTION_PRESSED = 'OTPAnswerSecurityQuestionPressed',
    REGISTRATION_PRESSED = 'RegistrationPressed',
    FINDUSER_PRESSED = 'FindUserPressed',
}
