export enum LandingPageActions {
    BENEFITS_CARD_PRESSED = 'benefitsCardPressed',
    CLAIM_DETAILS_PRESSED = 'claimDetailsPressed',
    EXPRESS_REFILL_PRESSED = 'ExpressRefillPressed',
    FIND_CARE_CARD_PRESSED = 'findCarePressed',
    GOTO_ONBOARD_PRESSED = 'gotoOnboardPressed',
    ID_CARD_PRESSED = 'idCardPressed',
    MAKE_PAYMENT_PRESSED = 'makeAPaymentPressed',
    MANAGE_AUTO_PRESSED = 'manageAutoPressed',
    MANAGE_PHARMACY_PRESSED = 'managePharmacyPressed',
    MESSAGE_CENTER_PRESSED = 'messageCenterPressed',
    PHARMACY_SEARCH_PRESSED = 'pharmacySearchPressed',
    PRICE_A_MED_PRESSED = 'priceAMedPressed',
    PRICE_A_MED_REFACTORED_PRESSED = 'priceAMedRefactoredPressed',
    PROFILE_PRESSED = 'profilePressed',
    REQUEST_NEW_PRESCRIPTION_PRESSED = 'requestNewPrescriptionPressed',
    RENEWAL_SOON_PRESSED = 'renewalSoonPressed',
    VIEW_CLAIMS_PRESSED = 'viewClaimsPressed',
}
