export enum ManageAutoActions {
    ADD_NEW_ADDRESS_PRESSED = 'manageAutoAddNewAddressPressed',
    ADD_NEW_PAYMENT_PRESSED = 'addNewPaymentPressed',
    ADD_EMAIL_ADDRESS_PRESSED = 'addEmailAddressPressed',
    ADD_TEXT_NUMBER_PRESSED = 'addTextNumberPressed',
    ADD_VOICE_NUMBER_PRESSED = 'addVoiceNumberPressed',
    AUTO_REFILL_TOGGLE_SWITCHED = 'ManageAutoRefillToggleSwitched',
    AUTO_RENEW_TOGGLE_SWITCHED = 'ManageAutoRenewToggleSwitched',
    CHANGE_ADDRESS_PRESSED = 'manageAutoChangeAddressPressed',
    CHANGE_PRESSED = 'changePaymentPressed',
    EDIT_ADDRESS_PRESSED = 'manageAutoEditAddressPressed',
    MEDICAL_PROFILE_SAVE_PRESSED = 'medicalProfileSavePressed',
    MEDICAL_PROFILE_SETUP_PRESSED = 'medicalProfileSetupPressed',
    EDIT_BANK_ACCOUNT_PRESSED = 'editBankAccountPressed',
    EDIT_CREDIT_CARD_PRESSED = 'editCreditCardPressed',
    SAVE_PRESSED = 'savePaymentPressed',
    TOU_PRESSED = 'termsOfUsePressed',
}
