export enum MoreMenuHotActions {
    ABOUT_APP_PRESSED = 'aboutAppHotPressed',
    ACCESSIBILITY_PRESSED = 'accessibilityHotPressed',
    BENEFITS_EXTERNAL_PRESSED = 'benefitsExternalPressed',
    CONTACT_US_PRESSED = 'contactUsHotPressed',
    FAQ_PRESSED = 'faqHotPressed',
    FIND_CARE_PRESSED = 'findCareHotPressed',
    LEGAL_DISCLAIMERS_PRESSED = 'legalDisclaimersHotPressed',
    LANGUAGES_PRESSED = 'languagesHotPressed',
    LOGOUT_PRESSED = 'logoutHotPressed',
    MESSAGE_US_PRESSED = 'messageUsHotPressed',
    NONDISCRIMINATION_PRESSED = 'nondiscriminationHotPressed',
    PHARMACY_PRESSED = 'moreMenuHotPharmacyPressed',
    PLAN_BENEFITS_PRESSED = 'planBenefitsHotPressed',
    PRIVACY_POLICY_PRESSED = 'privacyPolicyHotPressed',
    PROFILE_PRESSED = 'profileHotPressed',
    REQUEST_CALL_PRESSED = 'requestCallHotPressed',
    TERMS_OF_USE_PRESSED = 'termsOfUseHotPressed',
    VISIT_WEBSITE_PRESSED = 'visitWebsiteHotPressed',
    WASTE_FRAUD_ABUSE_PRESSED = 'wasteFraudAbuseHotPressed',
}

export enum MoreMenuColdActions {
    ADMIN_PANEL_PRESSED = 'adminPanelPressed',
    ABOUT_APP_PRESSED = 'aboutAppColdPressed',
    ACCESSIBILITY_PRESSED = 'accessibilityColdPressed',
    FAQ_PRESSED = 'faqColdPressed',
    FAQ_VISIT_WEBSITE_PRESSED_MULTI_STATE = 'faqVisitWebsiteColdPressedMultiState',
    FAQ_VISIT_WEBSITE_PRESSED_SINGLE_STATE = 'faqVisitWebsiteColdPressedSingleState',
    FIND_CARE_PRESSED = 'findCareColdPressed',
    LEGAL_DISCLAIMERS_PRESSED = 'legalDisclaimersColdPressed',
    LANGUAGES_PRESSED = 'languagesColdPressed',
    NONDISCRIMINATION_PRESSED = 'nondiscriminationColdPressed',
    PRIVACY_POLICY_PRESSED = 'privacyPolicyColdPressed',
    REGISTER_PRESSED = 'registerColdPressedMoreMenu',
    TERMS_OF_USE_PRESSED = 'termsOfUseColdPressed',
    RETURN_LOGIN_PRESSED = 'returnLoginColdPressed',
    VISIT_WEBSITE_PRESSED_MULTI_STATE = 'visitWebsiteColdPressedMultiState',
    VISIT_WEBSITE_PRESSED_SINGLE_STATE = 'visitWebsiteColdPressedSingleState',
    WASTE_FRAUD_ABUSE_PRESSED = 'wasteFraudAbuseColdPressed',
}

export enum MoreMenuAccessibilityColdActions {
    ALTERNATIVE_FORMAT_PRESSED = 'alternativeFormatColdPressed',
    GENERAL_ACCESSIBILITY_PRESSED = 'generalAccessibilityColdPressed',
    MOBILE_ACCESSIBILITY_PRESSED = 'mobileAccessibilityColdPressed',
    PDF_ACCESSIBILITY_PRESSED = 'pdfAccessibilityColdPressed',
    WEBSITE_ACCESSIBILITY_PRESSED = 'websiteAccessibilityColdPressed',
}
