export enum PaymentActions {
    ADD_PAYMENT_METHOD_PRESSED = 'addPaymentMethodPressed',
    AUTOMATIC_PAYMENTS_UNENROLL_PRESSED = 'automaticPaymentsUnenrollPressed',
    ADD_PHARMACY_PAYMENT_METHOD_PRESSED = 'addPaymentMethodPharmacyPressed',
    AGREE_AND_ENROLL_SPECIALTY_PRESSED = 'agreeAndEnrollSpecialtyPressed',
    BANK_ACCOUNT_EDIT_PRESSED = 'bankAccountEditPressed',
    CHANGE_PHARMACY_PAYMENT_METHOD_PRESSED = 'changePaymentMethodPharmacyPressed',
    MANAGE_PHARMACY_PAYMENT_METHOD_PRESSED = 'managePharmacyPaymentMethodPressed',
    CREDIT_CARD_EDIT_PRESSED = 'creditCardEditPressed',
    DONE_PRESSED = 'donePressed',
    GO_HOME_PRESSED = 'goHomePressed',
    MANAGE_AUTO_CANCEL_PRESSED = 'manageAutoCancelPressed',
    MANAGE_AUTO_SPECIALTY_PRESSED = 'manageAutoSpecialtyPressed',
    PAY_NOW_CANCEL_PRESSED = 'payNowCancelPressed',
    PAY_NOW_PHARMACY_PRESSED = 'payPharmacyPressed',
    PAYMENT_HISTORY_PRESSED = 'paymentHistoryPressed',
    PHARMACY_BANK_ACCOUNT_EDIT_PRESSED = 'pharmacyBankAccountEditPressed',
    PHARMACY_CREDIT_CARD_EDIT_PRESSED = 'pharmacyCreditCardEditPressed',
    SAVE_PRESSED = 'savePressed',
    SET_UP_AUTOMATIC_PAYMENTS_PRESSED = 'setUpAutomaticPaymentsPressed',
    SPECIALTY_PAY_NOW_CANCEL_PRESSED = 'specialtyCancelPressed',
    SPECIALTY_PAY_NOW_MULTIPLE_MEMBERS_PRESSED = 'paySpecialtyMultipleMembersPressed',
    SPECIALTY_PAY_NOW_PRESSED = 'paySpecialtyPressed',
    SUBMIT_PAYMENT_PRESSED = 'submitPaymentPressed',
    SUBMIT_SPECIALTY_PAYMENT_PRESSED = 'submitSpecialtyPaymentPressed',
}
