export enum PrescriptionsActions {
    ADD_NEW_ADDRESS_PRESSED = 'savingsOpportunityAddNewAddressPressed',
    CHANGE_ADDRESS_PRESSED = 'savingsOpportunityChangeAddressPressed',
    EDIT_ADDRESS_PRESSED = 'savingsOpportunityEditAddressPressed',
    FILTERS_PRESSED = 'filtersPressed',
    SAVING_OPPORTUNITY_HOME_DELIVERY_CONFIRMATION_PRESSED = 'savingsOpportunityHomeDeliveryConfirmationPressed',
    SAVING_OPPORTUNITY_HOME_DELIVERY_MORE_OPTIONS_PRESSED = 'savingsOpportunityHomeDeliveryMoreOptionsPressed',
    SAVING_OPPORTUNITY_HOME_DELIVERY_PRESCRIBER_SEARCH_PRESSED = 'savingsOpportunityHomeDeliveryPrescriberSearchPressed',
    SAVING_OPPORTUNITY_HOME_DELIVERY_PRESCRIBER_SEARCH_RESULT_PRESSED = 'savingsOpportunityHomeDeliveryPrescriberSearchResultPressed',
    SAVING_OPPORTUNITY_HOME_DELIVERY_PRESCRIBER_SELECT_PRESSED = 'savingsOpportunityHomeDeliveryPrescriberSelectPressed',
    SAVING_OPPORTUNITY_HOME_DELIVERY_PRESSED = 'savingOpportunityHomeDeliveryPressed',
    SAVING_OPPORTUNITY_HOME_DELIVERY_CANCEL_PRESSED = 'homeDeliveryCancelPressed',
    SAVING_OPPORTUNITY_OPTOUT_CANCEL_PRESSED = 'savingsOpportunityOptOutCancelPressed',
    SAVING_OPPORTUNITY_OPTOUT_PRESSED = 'savingsOpportunityOptOutPressed',
    SAVING_OPPORTUNITY_OPTOUT_SUBMIT_PRESSED = 'savingsOpportunityOptOutSubmitPressed',
    SAVING_OPPORTUNITY_PRESSED = 'savingsOpportunityPressed',
    SAVING_OPPORTUNITY_RETAIL_CANCEL_PRESSED = 'savingsOpportunityRetailCancelPressed',
    SAVING_OPPORTUNITY_RETAIL_PRESCRIBER_SEARCH_PRESSED = 'savingsOpportunityRetailPrescriberSearchPressed',
    SAVING_OPPORTUNITY_RETAIL_PRESCRIBER_SELECT_PRESSED = 'savingsOpportunityRetailPrescriberSelectPressed',
    SAVING_OPPORTUNITY_RETAIL_SEARCH_PRESSED = 'savingsOpportunityRetailSearchPressed',
    SAVING_OPPORTUNITY_RETAIL_SELECT_PRESSED = 'savingsOpportunityRetailSelectPressed',
    SAVING_OPPORTUNITY_RETAIL_SUBMIT_PRESSED = 'savingsOpportunityRetailSubmitPressed',
    SORTERS_PRESSED = 'sortersPressed',
}
