export enum RegistrationActions {
    ADD_ACCOUNT_RECOVERY_NUMBER_PRESSED = 'AddAccountRecoveryNumberPressed',
    ADD_ACCOUNT_RECOVERY_NUMBER_REGISTRATION_PRESSED = 'AddAccountRecoveryNumberRegistrationPressed',
    EDIT_YOUR_INFORMATION_CANCEL_PRESSED = 'EditYourInformationCancelPressed',
    EDIT_YOUR_INFORMATION_PRESSED = 'EditYourInformationPressed',
    EDIT_YOUR_INFORMATION_SAVE_PRESSED = 'EditYourInformationSavedPressed',
    ELIGIBILITY_FIND_MY_INFO_PRESSED = 'EligibilityFindMyInfoPressed',
    ELIGIBILITY_FIND_MY_INFO_PRESSED_2FA = 'EligibilityFindMyInfoPressed2FA',
    EMAIL_ADDRESS_CONTINUE_PRESSED = 'EmailAddressContinuePressed',
    EMAIL_ADDRESS_GO_TO_RECOVERY_NUMBER = 'EmailAddressGoToRecoveryNumber',
    REGISTRATION_CANCELED = 'Login',
    REGISTRATION_FIND_MY_INFO_2FA_SEND_CODE_PRESSED = 'Registration2FASendCodePressed',
    REGISTRATION_FIND_MY_INFO_ADD_NUMBER = 'Registration2FAAddNumberPressed',
    REGISTRATION_FIND_MY_INFO_CREATE_ACCOUNT = 'CreateAccountNext',
    REGISTRATION_FIND_MY_INFO_TWO_FACTOR_AUTH = 'TwoFactorAuthenticationNext',
    REGISTRATION_PRESSED = 'RegistrationPressed',
    REGISTRATION_SUCCESS_MODAL_PRESSED = 'RegistrationSuccessModalPressed',
    SECURITY_CODE_VALIDATE_SUCCESS = 'securityCodeValidateSuccess',
    SECURITY_QUESTIONS_CONTINUE_PRESSED = 'SecurityQuestionsContinuePressed',
    SECURITY_QUESTIONS_FAILURE_MODAL_PRESSED = 'Login',
    TERMS_OF_USE_PRESSED = 'TermsOfUsePressed',
    USERNAME_PASSWORD_CONTINUE_PRESSED = 'UsernamePasswordContinuePressed',
}
