export enum ReviewOrderActions {
    ADD_LOCATION_PRESSED = 'addLocationPressed',
    ADD_OR_EDIT_EMAIL_PRESSED = 'addOrEditEmailPressed',
    ADD_NEW_ADDRESS_OPTION_PRESSED = 'addNewAddressOptionPressed',
    ADD_NEW_PAYMENT_OPTION_PRESSED = 'addNewPaymentOptionPressed',
    CANCEL_EMAIL_PRESSED = 'cancelEmailPressed',
    CANCEL_ORDER_PRESSED = 'cancelOrderPressed',
    CHANGE_ADDRESS_OPTION_PRESSED = 'changeAddressOptionPressed',
    CHANGE_PAYMENT_OPTION_PRESSED = 'changePaymentOptionPressed',
    EDIT_ADDRESS_OPTION_PRESSED = 'editAddressOptionPressed',
    EDIT_BANK_ACCOUNT_PAYMENT_OPTION_PRESSED = 'editBankAccountPaymentOptionPressed',
    EDIT_CREDIT_CARD_PAYMENT_OPTION_PRESSED = 'editCreditCardPaymentOptionPressed',
    MORE_OPTIONS_PRESSED = 'moreOptionsPressed',
    SAVE_BUTTON_PRESSED = 'saveButtonPressed',
    SELECT_STORE_BUTTON_PRESSED = 'selectButtonPressed',
    SUBMIT_ORDER_PRESSED = 'submitOrderPressed',
    VIEW_PRESCRIPTIONS_PRESSED = 'viewPrescriptionsPressed',
    REVIEW_ORDER_VIEW_MEDICAL_PROFILE_PRESSED = 'reviewOrderViewMedicalProfilePressed',
    REVIEW_SWITCH_TO_90_MEDICAL_PROFILE_PRESSED = 'reviewSwitchTo90MedicalProfilePressed',
}
