import {
    AccountTypes,
    AddressType,
    CreditCard,
    initialCart,
    Languages,
    MedicalProfile,
    MemberContext,
    MemberPreferences,
    MemberProfile,
    PharmacyInfo,
    RegistrationData,
} from 'atlas-services/src/models';
import { AppState } from '../models';
import { deepClone } from '../utils';

export function getInitialAppState(selectedLanguage: Languages = Languages.EN): AppState {
    return {
        actionablePrescriptions: [],
        defaultPharmacy: {} as PharmacyInfo,
        filteredPharmacies: [],
        fupData: { firstName: '', lastName: '', username: '', question: { question: 'string', answer: '', id: '' } },
        idCards: [],
        isBiometricLogin: false,
        isLoggedIn: false,
        isScreenReaderEnabled: false,
        manageAutoCart: deepClone(initialCart),
        medicalProfiles: [] as MedicalProfile[],
        memberAddresses: [],
        memberContext: {
            memberInfo: {
                firstName: '',
            },
        } as MemberContext,
        memberPreferences: new MemberPreferences([], {}, {}),
        memberProfile: {} as MemberProfile,
        membersTOUStatus: [],
        nonActionablePrescriptions: [],
        optedOutPrescriptionId: '',
        payAccountBalanceCart: {
            amountDue: 0,
            paymentAmount: 0,
            selectedPbmPaymentMethod: null,
            selectedSpecialtyAccount: {
                accountBalance: '0',
                accountBalancePaymentInfo: {
                    achAuthorizationRequired: false,
                    recentPayment: false,
                    recentPaymentAmount: '0',
                },
                accountHolder: {
                    address: {
                        addressType: AddressType.HOME_ADDRESS,
                        city: '',
                        county: '',
                        id: '',
                        isDefaultAddress: false,
                        latitude: 0,
                        longitude: 0,
                        state: '',
                        storeName: '',
                        streetAddress1: '',
                        streetAddress2: '',
                        zipCode: '',
                        zipCodeSuffix: '',
                    },
                    dob: '',
                    emailAddress: '',
                    firstName: '',
                    lastName: '',
                    middleInitial: '',
                    middleName: '',
                    participantId: 0,
                    phoneExtension: '',
                    phoneNumber: '',
                },
                accountId: '',
                accountType: AccountTypes.CREDIT,
                isFlexSpendingAccount: false,
                lastPaymentAmount: '',
                memberUid: '',
                paymentMethods: [],
            },
            selectedSpecialtyPaymentMethod: null,
        },
        pbmAccountBalance: 0,
        pharmacies: [],
        prescriptionCart: deepClone(initialCart),
        registrationData: {
            accountRecovery: {
                wasSetEarly: false,
            },
            dateOfBirth: '',
            eligibility: {},
            emailAddress: '',
            password: '',
            questions: [],
            username: '',
        } as RegistrationData,
        selectedAddress: {
            addressType: AddressType.MAILING_ADDRESS,
            city: 'Norfolk',
            id: '11',
            isDefaultAddress: true,
            state: 'VA',
            streetAddress1: '1111 One St',
            zipCode: '11111',
        },
        selectedLanguage,
        selectedPaymentMethod: { accountName: '', isDefaultMethod: false, paymentType: null },
        selectedPharmacy: {} as PharmacyInfo,
        selectedSpecialtyPaymentMethod: null,
        specialtyAccountBalance: 0,
        twoFactorAuthenticationData: { contactInfo: [] },
        userData: { userName: '', password: '', planInfo: null },
    };
}
